name: Build exe file with Nuitka

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest

    steps:

      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Build python script into a single execute or app folder (macOS)
      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: SkillMacro.py
          mode: standalone
          enable-plugins: pyside6

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/*
          include-hidden-files: true