name: Package exe with PyInstaller - UPX

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.9.0'
          spec: 'SkillMacro.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'SkillMacro'
          options: -F, -w, --upx-dir ".\upx", -i ".\app\resources\image\icon.ico", --add-data "app;app"
