name: Package exe with PyInstaller - Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.9.0
          pip install -r requirements.txt

      - name: Create Executable
        run: pyinstaller --upx-dir "./upx" -F -w --clean -i="./app/resources/image/icon.ico" --add-data "app;app" SkillMacro.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: SkillMacro