name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.9.0'
          spec: 'SkillMacro.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'SkillMacro'
          options: --onefile, --name "SkillMacro", --windowed
